### PR TITLE
feat: improve style for archive page #105

### PR DESCRIPTION
**Pull request by MAHcodes**

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
image

I think I like the mobile one best, maybe also move the text and title to the start

**Comment by ChristianChiarulli** [comment]
or maybe just move the text to the start

**Comment by MAHcodes** [comment]
I can make option for the two different views on desktop

**Comment by MAHcodes** [comment]
now the user can choose the view he wants,
it saves his choice in the localstorage,
and this will work for the archive and the profile page, 
the only view for mobile is column

**Pull request merged**
